
BASE=/home/user/benchmark

.PHONY: all
all:
	@echo 'make install' to copy scripts to where they should be.

.PHONY: install
install:
	cp macro.sh $(BASE)/
	cp run-filebench.sh $(BASE)/filebench-run/
	cp run-postmark.sh $(BASE)/postmark-1.53/

